default["redis2"]["install_from"] = "package"
default["redis2"]["log_dir"] =  "/var/log/redis"
default["redis2"]["conf_dir"] = "/etc/redis"
default["redis2"]["pid_dir"] = "/var/run/redis"
default["redis2"]["data_dir"] = nil # setup by volume_dirs
default["redis2"]["user"] =     "redis"
default["redis2"]["deamon"] = "redis-server"
default["redis2"]["instances"]["default"]["daemonize"] = "no"
default["redis2"]["instances"]["default"]["bindaddress"] = "0.0.0.0"
default["redis2"]["instances"]["default"]["port"] = "6379"
default["redis2"]["instances"]["default"]["timeout"] = 300
default["redis2"]["instances"]["default"]["loglevel"] = "notice"
default["redis2"]["instances"]["default"]["logfile"] = "stdout"
default["redis2"]["instances"]["default"]["syslog-enabled"] = "no"
default["redis2"]["instances"]["default"]["syslog-ident"] = "redis"
default["redis2"]["instances"]["default"]["syslog-facility"] = "USER"
default["redis2"]["instances"]["default"]["bgsave"] = ["900 1", "300 10", "60 10000"]
default["redis2"]["instances"]["default"]["rdbcompression"] = "yes"
default["redis2"]["instances"]["default"]["dumpdb_filename"] = "dump.rdb"
default["redis2"]["instances"]["default"]["slave-serve-stale-data"] = "yes"
default["redis2"]["instances"]["default"]["slave-read-only"] = "no"
default["redis2"]["instances"]["default"]["activerehashing"] = "yes" # no to disable, yes to enable
default["redis2"]["instances"]["default"]["databases"] = 16

default["redis2"]["instances"]["default"]["appendonly"] = "no"
default["redis2"]["instances"]["default"]["appendfsync"] = "everysec"
default["redis2"]["instances"]["default"]["no_appendfsync_on_rewrite"] = "no"

default["redis2"]["instances"]["default"]["maxmemory_samples"] = 3
default["redis2"]["instances"]["default"]["maxmemory_policy"] = "volatile-lru"
